FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY __init__.py main.py requirements.txt /app/
COPY tests/ /app/tests/

RUN pip install -r requirements.txt
RUN ls -la /app && sleep 5
CMD ["pytest", "-v"]